### ISSUE TITLE
Can't access git url

### ISSUE THREAD

**Issue by jadedevin13** [cozy-labs/cozy-docker#17]
``` shell
info - data-system:git clone
error - Error: Can't access to git url: https://github.com/cozy/cozy-data-system.git
Sending error to client: 
Error: Can't access to git url: https://github.com/cozy/cozy-data-system.git
    at Request._callback (/usr/local/lib/node_modules/cozy-controller/build/server/lib/git.js:46:13)
    at Request.self.callback (/usr/local/lib/node_modules/cozy-controller/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cozy-controller/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cozy-controller/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
[Thu, 17 Dec 2015 00:52:03 GMT] - POST /drones/data-system/start - 400 - 137339.784 ms -  938
error - An error occured:
error - Install failed for data-system.
[Error: Can't access to git url: https://github.com/cozy/cozy-data-system.git]
error - An error occured:
error - Install failed for data-system.
The command '/bin/sh -c su - couchdb -c 'couchdb -b'  && sleep 5  && while ! curl -s 127.0.0.1:5984; do sleep 5; done  && /usr/local/lib/node_modules/cozy-controller/bin/cozy-controller & sleep 5  && while ! curl -s 127.0.0.1:9002; do sleep 5; done  && cd /usr/local/cozy-indexer/cozy-data-indexer  && . ./virtualenv/bin/activate  && /usr/local/cozy-indexer/cozy-data-indexer/virtualenv/bin/python server.py & sleep 5  && while ! curl -s 127.0.0.1:9102; do sleep 5; done  && cozy-monitor install data-system  && cozy-monitor install home  && cozy-monitor install proxy' returned a non-zero code: 1
```

**Comment by jadedevin13** [comment]
It plays between the error on the description and this one down here.

``` bash
info - data-system:git clone
info - data-system:npm install
[Thu, 17 Dec 2015 01:06:26 GMT] - POST /drones/data-system/start - - - - ms -  -
error - An error occured:
error - An error occured:
error - Install failed for data-system.
error - Install failed for data-system.
[Error: Install failed for data-system.
Default git repo https://github.com/cozy/cozy-data-system.git doesn't exist.
You can use option -r to use a specific repo.]
The command '/bin/sh -c su - couchdb -c 'couchdb -b'  && sleep 5  && while ! curl -s 127.0.0.1:5984; do sleep 5; done  && /usr/local/lib/node_modules/cozy-controller/bin/cozy-controller & sleep 5  && while ! curl -s 127.0.0.1:9002; do sleep 5; done  && cd /usr/local/cozy-indexer/cozy-data-indexer  && . ./virtualenv/bin/activate  && /usr/local/cozy-indexer/cozy-data-indexer/virtualenv/bin/python server.py & sleep 5  && while ! curl -s 127.0.0.1:9102; do sleep 5; done  && cozy-monitor install data-system  && cozy-monitor install home  && cozy-monitor install proxy' returned a non-zero code: 1
```

**Comment by nono** [comment]
Hello,

thanks for the feedback. It looks weird that doing a git clone fails like this (the URL is good). Can you try to do this command to see if a warning is shown:

``` sh
git clone https://github.com/cozy/cozy-data-system.git
```

**Comment by jadedevin13** [comment]
I'm not doing it manually it's from the command 

```
cozy-monitor install data-system
```

line 101 from this [Dockerfile](https://github.com/cozy-labs/cozy-docker/blob/master/Dockerfile)

I'm just running it with the command

```
sudo docker build -t cozy/full github.com/cozy-labs/cozy-docker
```

**Comment by nono** [comment]
Sure. But I don't have the same error and I'd like to have more informations on what happens. If you run the command above, maybe we can see an hint on what is the real error.

**Comment by jadedevin13** [comment]
Will give an update later I feel it's just because of the internet. Country: Philippines. :1234:

**Comment by jadedevin13** [comment]
It's now working just can't install apps in the store simultaneously.
