### ISSUE TITLE
Image build failed

### ISSUE THREAD

**Issue by spiroid** [cozy-labs/cozy-docker#9]
Steps to reproduce:
-  `git pull git@github.com:cozy-labs/cozy-docker.git`
- `cd cozy-docker`
- `docker build -t cozy/full .`

It fails on step 15 with the following error messages: 

```
Step 15 : RUN su - couchdb -c 'couchdb -b'  && sleep 5  && while ! curl -s 127.0.0.1:5984; do sleep 5; done  && /usr/local/lib/node_modules/cozy-controller/bin/cozy-controller & sleep 5  && while ! curl -s 127.0.0.1:9002; do sleep 5; done  && cd /usr/local/cozy-indexer/cozy-data-indexer  && . ./virtualenv/bin/activate  && /usr/local/cozy-indexer/cozy-data-indexer/virtualenv/bin/python server.py & sleep 5  && while ! curl -s 127.0.0.1:9102; do sleep 5; done  && cozy-monitor install data-system  && cozy-monitor install home  && cozy-monitor install proxy
 ---> Running in 177026e5960d
Apache CouchDB has started, time to relax.
{"couchdb":"Welcome","uuid":"2ff20cff2b2d3de8971c5513e2ae7a19","version":"1.5.0","vendor":{"version":"14.04","name":"Ubuntu"}}
info - ### FILE INITIALIZATION ###
info - init: source directory
info - init: stack file
info - init : token file
info - ### AUTOSTART ###
info - couchDB: started
info - Stack isn't installed
info - ### Start Cozy Controller ###
[2015-08-01 20:52:04:874] info - americano | Routes loaded.
[2015-08-01 20:52:04:875] info - americano | Configuration for production loaded.
[2015-08-01 20:52:04:876] info - americano | controller server is listening on port 9002...
Error: Cannot find module '../../package.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.module.exports.index [as handle] (/usr/local/lib/node_modules/cozy-controller/build/server/controllers/index.js:5:16)
    at next_layer (/usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/route.js:107:5)
    at /usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/index.js:213:24
    at Function.proto.process_params (/usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/index.js:284:12)
    at next (/usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/index.js:207:19)
Internal Server Error[Sat, 01 Aug 2015 20:52:09 GMT] - GET / - 500 - 8.129 ms -  21
[I 150801 20:52:09 server:25] Cozy Data Indexer started on port 9102.
Cozy Data Indexer v1.0.6[I 150801 20:52:14 web:1462] 200 GET / (127.0.0.1) 0.32ms
info - Install started for data-system...
error - Error: Cannot uninstall an application not installed
Sending error to client :
Error: Error: Cannot uninstall an application not installed
    at /usr/local/lib/node_modules/cozy-controller/build/server/controllers/applications.js:152:13
    at Object.module.exports.uninstall (/usr/local/lib/node_modules/cozy-controller/build/server/lib/controller.js:356:14)
    at Object.module.exports.uninstall [as handle] (/usr/local/lib/node_modules/cozy-controller/build/server/controllers/applications.js:149:21)
    at next_layer (/usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/route.js:103:13)
    at Object.module.exports.check [as handle] (/usr/local/lib/node_modules/cozy-controller/build/server/middlewares/token.js:31:16)
    at next_layer (/usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/route.js:107:5)
    at /usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/index.js:213:24
    at param (/usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/index.js:303:14)
    at param (/usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/index.js:319:14)
[Sat, 01 Aug 2015 20:52:14 GMT] - POST /drones/data-system/clean - 400 - 1.670 ms -  1515
info - data-system:git clone
info - data-system:npm install
info - npm:install:success
info - data-system:start application
[Sat, 01 Aug 2015 20:52:41 GMT] - POST /drones/data-system/start - 200 - 26376.685 ms -  23
info - data-system was successfully installed.
info - Install started for home...
error - Error: Cannot uninstall an application not installed
Sending error to client :
Error: Error: Cannot uninstall an application not installed
    at /usr/local/lib/node_modules/cozy-controller/build/server/controllers/applications.js:152:13
    at Object.module.exports.uninstall (/usr/local/lib/node_modules/cozy-controller/build/server/lib/controller.js:356:14)
    at Object.module.exports.uninstall [as handle] (/usr/local/lib/node_modules/cozy-controller/build/server/controllers/applications.js:149:21)
    at next_layer (/usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/route.js:103:13)
    at Object.module.exports.check [as handle] (/usr/local/lib/node_modules/cozy-controller/build/server/middlewares/token.js:31:16)
    at next_layer (/usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/route.js:107:5)
    at /usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/index.js:213:24
    at param (/usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/index.js:303:14)
    at param (/usr/local/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/index.js:319:14)
[Sat, 01 Aug 2015 20:52:41 GMT] - POST /drones/home/clean - 400 - 0.546 ms -  1515
info - home:git clone
[Sat, 01 Aug 2015 21:02:41 GMT] - POST /drones/home/start - - - - ms -  -
error - An error occured:
error - Install failed for home.
[Error: Error: socket hang up]
INFO[0642] The command [/bin/sh -c su - couchdb -c 'couchdb -b'  && sleep 5  && while ! curl -s 127.0.0.1:5984; do sleep 5; done  && /usr/local/lib/node_modules/cozy-controller/bin/cozy-controller & sleep 5  && while ! curl -s 127.0.0.1:9002; do sleep 5; done  && cd /usr/local/cozy-indexer/cozy-data-indexer  && . ./virtualenv/bin/activate  && /usr/local/cozy-indexer/cozy-data-indexer/virtualenv/bin/python server.py & sleep 5  && while ! curl -s 127.0.0.1:9102; do sleep 5; done  && cozy-monitor install data-system  && cozy-monitor install home  && cozy-monitor install proxy] returned a non-zero code: 1 
```

**Comment by clochix** [comment]
Thanks for reporting @spiroid,
Seems like a strange bug with `cozy-controller` :-S @aenario or @poupotte, would you mind having a look at this please ?

**Comment by spiroid** [comment]
@clochix some update about that issue.

I cleaned my docker environment and removed all cozy related images and orphans. Then i triggered a new build yesterday which completed successfully.

Maybe the build issue was related to some cluttered file in one layer and the clean operation was helpful. 

Or maybe it was related to cozy components versions available at the previous build time that changed. In that case it may be a good idea to freeze some components version at the image build time (cozy controller / cozy monitor).

Anyway, as the build works, this issue can be closed.

**Comment by frankrousseau** [comment]
Thank you @spiroid for your report!
